### PR TITLE
refactored drawing and updating of foods

### PR DESCRIPTION
**Pull request by cconcannon**
I refactored methods applicable to both Junk foods and Health foods so that you avoid repeating much of the same code that calls for drawing and updating positions. Let me know what you think! @neight-allen @chompasina 

Unfortunately the test suite was not running at the time of refactoring, so I was unable to verify that the changes don't break the code... however, the game plays exactly the same as when I started (as far as I can tell).

### CODE REVIEW

**Comment by chompasina** [comment]
This looks great, @concach! We're going to play around with these refactors locally and see how they do with our tests. Thanks for your hard work on it!

**Review by neight-allen — COMMENTED** [review]
A few thoughts:
- I think I like the direction of merging health foods and junk foods. This works especially well if both `HealthFood`s and `JunkFood`s have the same methods and properties (`move`, `draw`, `type`, etc).
- You can further simplify your draw methods by matching `type` to the name of the image. Like: `foodImage.src = '../images/' + food.type + '.png'`

Keep at it. This code is going to be super clean!

**Comment by chompasina** [comment]
Thanks for your response @neight-allen ! @deborahleehamel, @karinamzalez and I started refactoring on a different path so we're going to close this PR but so appreciate the feedback and suggestions as they got us going in the right direction. This code is getting squeaky clean!

**Comment by cconcannon** [comment]
Glad I could help! and @neight-allen 's suggestion to concatenate the food type into a string format directly _just_ might be that workaround that we were trying to come up with earlier. Good luck!

**Comment by chompasina** [comment]
@concach yeah! We ended up doing exactly that--concatenating the strings in the image source paths. Thanks again. :)

**Pull request closed without merging**
